// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ${defaultTargetPlatform.name} - '
          'this app is configured for Android only.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRv5e65fi49acdjMe6fC6wv_FyI360_JM',
    appId: '1:421099113193:android:1031456da72236da7dfe78',
    messagingSenderId: '421099113193',
    projectId: 'pasabay-c7384',
    storageBucket: 'pasabay-c7384.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPgivR9TGUwg-Y5lESOKF9ypSApfuhGCA',
    appId: '1:421099113193:web:a6bc628a0c3067b07dfe78',
    messagingSenderId: '421099113193',
    projectId: 'pasabay-c7384',
    authDomain: 'pasabay-c7384.firebaseapp.com',
    storageBucket: 'pasabay-c7384.firebasestorage.app',
  );

}